/* Auto-generated by genmsg_cpp for file /home/tfv1/Desktop/module_ros/beego/msg/velocity.msg */
#ifndef BEEGO_MESSAGE_VELOCITY_H
#define BEEGO_MESSAGE_VELOCITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace beego
{
template <class ContainerAllocator>
struct velocity_ {
  typedef velocity_<ContainerAllocator> Type;

  velocity_()
  : trans_vel(0.0)
  , rot_vel(0.0)
  {
  }

  velocity_(const ContainerAllocator& _alloc)
  : trans_vel(0.0)
  , rot_vel(0.0)
  {
  }

  typedef float _trans_vel_type;
  float trans_vel;

  typedef float _rot_vel_type;
  float rot_vel;


private:
  static const char* __s_getDataType_() { return "beego/velocity"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a9a36d4aead03174102ed0f5686cc73d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 trans_vel\n\
float32 rot_vel\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, trans_vel);
    ros::serialization::serialize(stream, rot_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, trans_vel);
    ros::serialization::deserialize(stream, rot_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(trans_vel);
    size += ros::serialization::serializationLength(rot_vel);
    return size;
  }

  typedef boost::shared_ptr< ::beego::velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beego::velocity_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct velocity
typedef  ::beego::velocity_<std::allocator<void> > velocity;

typedef boost::shared_ptr< ::beego::velocity> velocityPtr;
typedef boost::shared_ptr< ::beego::velocity const> velocityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beego::velocity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beego::velocity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beego

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beego::velocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beego::velocity_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beego::velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a9a36d4aead03174102ed0f5686cc73d";
  }

  static const char* value(const  ::beego::velocity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa9a36d4aead03174ULL;
  static const uint64_t static_value2 = 0x102ed0f5686cc73dULL;
};

template<class ContainerAllocator>
struct DataType< ::beego::velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beego/velocity";
  }

  static const char* value(const  ::beego::velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beego::velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 trans_vel\n\
float32 rot_vel\n\
\n\
";
  }

  static const char* value(const  ::beego::velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::beego::velocity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beego::velocity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.trans_vel);
    stream.next(m.rot_vel);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct velocity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beego::velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beego::velocity_<ContainerAllocator> & v) 
  {
    s << indent << "trans_vel: ";
    Printer<float>::stream(s, indent + "  ", v.trans_vel);
    s << indent << "rot_vel: ";
    Printer<float>::stream(s, indent + "  ", v.rot_vel);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEEGO_MESSAGE_VELOCITY_H

